#服务启动端口
server:
  port: 9100

# mysql
spring:
  datasource:
    url: jdbc:mysql://218.17.189.13:3336/epoch?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: epoch
    password: epoch12345