#服务启动端口
server:
  port: 9100

# mysql
spring:
  datasource:
    url: jdbc:mysql://47.96.20.71:3306/credit_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: solo
    password: solo!#2019_solo!