#服务启动端口
server:
  port: 8980

# mysql
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/epoch?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 123456